name: configs/EmoryTargets.yaml
runname: EmoryTargets
parentID: syn21532475
runID: EmoryTargets
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: ~/AD_TargetRank

figures: runs/figures
tables: runs/tables

genelistfile: EmoryTargets.txt
genelisttype: GNAME


modules:
  - 7
