name: configs/M62.yaml
runname: M62
parentID: syn21532475
runID: M62
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: ~/AD_TargetRank

figures: runs/figures
tables: runs/tables

genelistfile: ModuleM62.txt
genelisttype: GNAME


modules:
  - 7
