name: configs/Moesin.yaml
runname: Moesin
parentID: syn21532475
runID: Moesin
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: ~/AD_TargetRank

figures: runs/figures
tables: runs/tables

genelistfile: genelists/Moesin.txt
genelisttype: GNAME


modules:
  - 7
