name: configs/pQTL.yaml
runname: pQTL
parentID: syn21532475
runID: pQTL
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: ~/AD_TargetRank

figures: runs/figures
tables: runs/tables

genelistfile: genelists/pQTL.txt
genelisttype: GNAME


modules:
  - 7
