name: configs/Retromer.yaml
runname: Retromer
parentID: syn21532475
runID: Retromer
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: ~/AD_TargetRank

figures: runs/figures
tables: runs/tables

genelistfile: Retromer.txt
genelisttype: GNAME


modules:
  - 7
