name: configs/TestConfig.yaml
runname: Test
parentID: syn21532475
runID: Test
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: /home/jgockley/AD_TargetRank

figures: runs/figures
tables: runs/tables

genelistfile: genelists/ENSGtest.txt
genelisttype: ENSG


modules:
  - 3
  - 4
  - 5
  - 6
  - 7

  
