name: configs/TestConfig.yaml
runname: Test
parentID: syn21532475
runID: Test
tissue:
  - CBE
  - DLPFC
  - FP
  - IFG
  - PHG
  - STG
  - TCX

filedir: ~/AD_TargetRank

figures: runs/figures
tables: runs/tables

